[entities]

Adresse
Age
Cp
Date
Id
Lieu
Mail
Nationalite
Organisation
Pays
Personne
Profession
Telephone
Ville

Anatomie
Dose
Duree
Examen
Frequence
Mode
Organisme
Pathologie
Sosy
Substance
Traitement
Valeur


[attributes]

categorie	Arg:Id, Value:email|numero
type	Arg:Lieu, Value:adresse|pays|ville
role	Arg:Personne, Value:patient|soignant|autre|inconnu

[relations]

<OVERLAP> Arg1:Adresse|Age|Cp|Date|Faux|Id|Lieu|Mail|Nationalite|Organisation|Pays|Personne|Profession|Telephone|Ville|Anatomie|Dose|Duree|Examen|Frequence|Mode|Organisme|Pathologie|Sosy|Substance|Traitement|Valeur,Arg2:Adresse|Age|Cp|Date|Faux|Id|Lieu|Mail|Nationalite|Organisation|Pays|Personne|Profession|Telephone|Ville|Anatomie|Dose|Duree|Examen|Frequence|Mode|Organisme|Pathologie|Sosy|Substance|Traitement|Valeur, <OVL-TYPE>:contain|equal|cross


[events]
