[entities]

Adresse
Age
Cp
Date
Email
Id
Lieu
Nationalite
Organisation
Pays
Personne
Profession
Telephone
URL
Ville
Faux


[attributes]

categorie	Arg:Id, Value:email|numero
type	Arg:Lieu, Value:adresse|pays|ville
role	Arg:Personne, Value:patient|soignant|autre|inconnu

[relations]

<OVERLAP> Arg1:Adresse|Age|Cp|Date|Email|Faux|Id|Lieu|Nationalite|Organisation|Pays|Personne|Profession|Telephone|URL|Ville,Arg2:Adresse|Age|Cp|Date|Email|Faux|Id|Lieu|Nationalite|Organisation|Pays|Personne|Profession|Telephone|URL|Ville, <OVL-TYPE>:contain|equal|cross


[events]
