[entities]

Adresse
Age
Cp
Date
Id
Lieu
Mail
Organisation
Pays
Personne
Telephone
Ville
Faux
Erreur


[attributes]

categorie	Arg:Id, Value:email|numero
type	Arg:Lieu, Value:adresse|pays|ville
role	Arg:Personne, Value:patient|soignant|autre|inconnu

[relations]

<OVERLAP> Arg1:Adresse|Age|Cp|Date|Faux|Id|Lieu|Mail|Organisation|Pays|Personne|Telephone|Ville,Arg2:Adresse|Age|Cp|Date|Faux|Id|Lieu|Mail|Organisation|Pays|Personne|Telephone|Ville, <OVL-TYPE>:contain|equal|cross


[events]
