[labels]

Adresse | Adresse | Adr
Age | Age | Age
Cp | Code postal | CP
Date | Date | Date
Email | Email | Mail
Faux | Faux positif | Faux
Id | Identifiant | Id
Lieu | Lieu | Lieu
Nationalite | Nationalité | Nat
Organisation | Organisation | Org
Pays | Pays | Pays
Personne | Personne | Pers
Profession | Profession | Pro
Telephone | Téléphone | Tel
URL | URL | url
Ville | Ville | Ville


[drawing]
Adresse	bgColor:#ff9999
Age	bgColor:#dd99aa
Cp	bgColor:#ffcc99
Date	bgColor:#99dddd
Email	bgColor:#999999
Faux	bgColor:#ffff99
Id	bgColor:#9999cc
Lieu	bgColor:#ddddff
Nationalite	bgColor:#ddffdd
Organisation	bgColor:#ddaadd
Pays	bgColor:#ddddff
Personne	bgColor:#ddffaa
Profession	bgColor:#ffff77
Telephone	bgColor:#ffddaa
URL	bgColor:#999999
Ville	bgColor:#ffddaa
