[labels]

Adresse | Adresse | Adr
Age | Age | Age
Cp | Code postal | CP
Date | Date | Date
Erreur | Erreur | Erreur
Faux | Faux positif | Faux
Id | Identifiant | Id
Lieu | Lieu | Lieu
Mail | e-mail | Mail
Pays | Pays | Pays
Personne | Personne | Pers
Organisation | Organisation | Org
Telephone | Téléphone | Tel
Ville | Ville | Ville


[drawing]
Adresse	bgColor:#ff9999
Age	bgColor:#dd99aa
Cp	bgColor:#ffcc99
Date	bgColor:#99dddd
Erreur	bgColor:#ffddff
Faux	bgColor:#ffff99
Id	bgColor:#9999cc
Lieu	bgColor:#ddddff
Mail	bgColor:#cc9933
Organisation	bgColor:#ddaadd
Pays	bgColor:#ddddff
Personne	bgColor:#ddffaa
Telephone	bgColor:#ffddaa
Ville	bgColor:#ffddaa
